Issue #3089823: Delete action is not performed if not after change action
BurdaMagazinOrg/module-update_helper pull request #19
Opened 2020-03-02 12:55 UTC by mtodor

Problem is described here: https://www.drupal.org/project/update_helper/issues/3089823

PR includes the following:
- test for the described problem
- handling of applied configuration changes. First, all changes will be applied and then new configuration will be verified against active configuration and only if it's exactly same, it will be marked as update was already successfully applied.

2020-03-03 09:53 UTC, dbosen commented on src/ConfigHandler.php
> +      'delete' => [],
Could you explain the order change? I don't understand it.

2020-03-03 12:24 UTC, dbosen commented on tests/src/Kernel/UpdaterTest.php
> +    file_put_contents($patch_file_path, $yml_serializer->encode(
encode() is a static function.

2020-03-03 12:36 UTC, dbosen requested changes

2020-03-03 12:36 UTC, dbosen commented on tests/src/Kernel/UpdaterTest.php
> +    file_put_contents($patch_file_path, $yml_serializer->encode($this->getUpdateDefinition()));
encode() is a static function.

2020-03-03 16:18 UTC, mtodor commented
Update Tests on Thunder 2
https://travis-ci.org/BurdaMagazinOrg/thunder-distribution/jobs/657793744?utm_medium=notification&utm_source=github_status

2020-03-04 09:35 UTC, mtodor commented
Here is Test on Thunder 3:
https://travis-ci.com/thunder/thunder-distribution/jobs/293482614

2020-03-04 15:46 UTC, dbosen approved these changes
lgtm

2020-03-05 08:50 UTC, merged