Issue #3018723 by mtodor: Fix Travis CI integration
BurdaMagazinOrg/module-update_helper pull request #3
Opened 2018-12-07 10:30 UTC by mtodor

2018-12-08 09:14 UTC, dbosen requested changes

2018-12-08 09:14 UTC, dbosen commented on .travis.yml
> +    - DRUPAL_TRAVIS_TEST_GROUP=update_helper,update_helper_checklist
This is now only needed if you want to restrict the tests. If you just want to run all tests (including submodules), this could be left out.

2018-12-08 09:14 UTC, dbosen commented on .travis.yml
> +  - composer global require thunder/travis @beta
@beta is not needed anymore

2018-12-10 09:04 UTC, mtodor commented
Looks good.

We should close PR #1 then.

2018-12-10 09:09 UTC, dbosen approved these changes

2018-12-10 09:15 UTC, merged